parameters:
#    isri_sid_pla_admin.example.class: ISRI\SidPla\AdminBundle\Example

services:
#    isri_sid_pla_admin.example:
#        class: %isri_sid_pla_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
