parameters:
#    isri_sid_pla_pao.example.class: ISRI\SidPla\PaoBundle\Example

services:
#    isri_sid_pla_pao.example:
#        class: %isri_sid_pla_pao.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
