parameters:
#    isri_sid_pla_unidad_org.example.class: ISRI\SidPla\UnidadOrgBundle\Example

services:
#    isri_sid_pla_unidad_org.example:
#        class: %isri_sid_pla_unidad_org.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
